name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
jobs:
  build:
    name: Allure Report-Standalone-service

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.13.0]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
          ref: gh-pages
          path: gh-pages      
    - name: Install Dependencies
      run: npm install

    - name: Executing the Test Scripts
      run: npm run wdio 
      
    - name: Allure report action from market place
      uses: simple-elf/allure-report-action@master
      if: always()
      #id: allure-report
      with:
         allure_results: test\.artifacts\allure-report
         #gh_pages: gh-pages
         #allure_report: allure-report
         allure_history: allure-history
         keep_reports: 20
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
       PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       PUBLISH_BRANCH: gh-pages
       PUBLISH_DIR: test\.artifacts\allure-report
    - name: Post the link to the report
      if: always()
      uses: Sibz/github-status-action@v1
      with: 
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}
